openapi: 3.0.0

info:
  title: "TEST"
  description: "Testing"
  version: "1.0"
  contact:
    email: "restapi@arburg.com"
  license:
    name: "ARBURG internal use only"
    url: "http://www.arburg.com/licenses/restapi-v1.0.html"
  termsOfService: "http://www.arburg.com/licenses/restapi-terms.html"

servers:
  - url: https://localhost:9443/sandbox/rest/api/v1

tags: 
  - name: Test
  
security:
  - OAuth2:
    - splicexuser

paths:

  /:
    get:
      summary: Get root
      description: Get root
      operationId: getRoot
      tags:
      - Test
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
        500:
          description: Server error  
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"      

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://arburg-splicex-ibm-garage.com/oauth2/endpoint/I4P/authorize'
          tokenUrl: 'https://arburg-splicex-ibm-garage.com/oauth2/endpoint/I4P/token'
          scopes:
            splicexuser: User profile information
            splicexserviceinfo: Service subscription information
            splicexserviceroles: Service roles and rights for this service

  schemas:
    Error:
      description: Generic error message
      type: object
      required:
        - code
        - message
        - timestamp
      properties:
        code:
          type: string
          description: Unique error code. Used to locate the error source.
        message:
          type: string
          description: Localised error message
        timestamp:
          type: string
          description: The time when the error occured. Used to find further infos in logging. yyyy-MM-dd HH:mm:ss.SSS
        email:
          type: string
          format: email
          description: The email address of the current user
